format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  frontend:                                             # name of the pipeline job that will be showing on UI
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/DRT9999/Ansible_App.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PSW: "AES:SS7p90H4or+Zuak2GLz48g==:4bbBfBxG8QllHnnNFoRJ6g=="
        #vault_token: "AES:0MnF+owJSEFkTnSRpoRm3Q==:XnoIrHIhEi1FmIt2UFmPY8rf+H03P2Pv7VE7SRt4Zus="
    environment_variables:
        COMPONENT: frontend
    template: App-Deployment-Template